services:
  frontend:
    build: frontend
    ports:
      - "4200:4200"
    container_name: frontend
    restart: always
  backend:
    build: backend
    ports:
      - "3000:3000"
    container_name: backend
    restart: always
    links:
      - database
  database:
    build: db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mean-db
    restart: always
